### ISSUE TITLE
Add direction arrow to map

### ISSUE THREAD

**Issue by mmlakin** [CodeArc13/PyDWMG#17]
Calculate direction player is moving and draw an arrow to indicate

**Comment by CodeArc13** [comment]
We need a way to determine if the previous location is from the previous zone or the zone we are actually in otherwise we will be generating invalid direction markers, in the VB version I used a bool called JustZoned which I set to True after each zoning but I think we could achieve this effect by setting the previous location to (None, None, None) on zoning like I have just done for when there is only one loc and then testing for this which would cover both the single loc after loading the mapper and zoning cases.

**Comment by CodeArc13** [comment]
As to last comment if we do this we will probably need to make prev_loc's scope a bit wider so it is more persistent and accessible outside of update_loc and settable from update_zone.

**Comment by CodeArc13** [comment]
I think I have fixed this issue by setting the self.current_loc = (None, None, None) in update zone, which makes sense as the last current loc would be for the last zone and therefore invalid.

**Comment by mmlakin** [comment]
I think we can just set current loc to none on zone change and that will take care of it, and add check for None in update loc

**Comment by CodeArc13** [comment]
Done and done

**Comment by mmlakin** [comment]
Just checked this out and it works perfectly!  I noticed some deprecation errors since drawline wants ints instead of floats, so I rounded the floats down as late as possible to get rid of the error messages

**Comment by CodeArc13** [comment]
> 
> 
> Just checked this out and it works perfectly! I noticed some deprecation errors since drawline wants ints instead of floats, so I rounded the floats down as late as possible to get rid of the error messages

Yes, I added an issue for this after i committed, not sure if we need to round to closest or up or down or just truncate for most accuracy, https://github.com/CodeArc13/PyDWMG/issues/19
