### ISSUE TITLE
Add automatic log switching

### ISSUE THREAD

**Issue by mmlakin** [CodeArc13/PyDWMG#27]

**Comment by mmlakin** [comment]
@CodeArc13 I added basic functionality in branch [automatic_log_file](https://github.com/CodeArc13/PyDWMG/commit/991bc5d027ddec6403e6f15c1eda65e23cf5ef42), give it a test when you can.

**Comment by mmlakin** [comment]
The print messages show the new parser starting before the old one stops, so I think I need to use a PyQt wait for thread feature I read about but can't remember offhand

**Comment by CodeArc13** [comment]
Tested it with multiple characters that are in zones that have and do not have maps in DWMG works great

**Comment by CodeArc13** [comment]
Also would it be a good idea to start using QSettings to store this instead of a plain text file as we want to have persistent settings for other things like window location and transparency.  We could either use QSettings or implement our own text/ini file which would be easier to manually edit as I think in Windows these settings are buried in the registry with QSettings but in Linux they are an ini file.  I am fine either way with either option but QSettings is a ready to go solution all we would need is a way to reset things like window location for situations where the window goes offscreen, as per my comment https://github.com/CodeArc13/PyDWMG/issues/24#issuecomment-850958210

**Comment by mmlakin** [comment]
looks good, thanks for testing
